// mockBook.js
// Contains a mockBooks array with sample book data for the library system.
// Used for demonstration and development purposes.

export const mockBooks = [
    {
        id: 1,
        cover_img: "https://covers.openlibrary.org/b/id/8798095-L.jpg",
        title: "On Grand Strategy",
        author: "John Lewis Gaddis",
        description: "A profound exploration of leadership and strategic thinking through historical lenses.",
        rating: 4.5,
        genre: "History",
    },
    {
        id: 2,
        cover_img: "https://covers.openlibrary.org/b/id/10515327-L.jpg",
        title: "The Art of War",
        author: "Sun Tzu",
        description: "Ancient military treatise on tactics and strategy, still relevant today.",
        rating: 4.7,
        genre: "Philosophy",
    },
    {
        id: 3,
        cover_img: "https://covers.openlibrary.org/b/id/8231856-L.jpg",
        title: "Thinking, Fast and Slow",
        author: "Daniel Kahneman",
        description: "A deep dive into the dual systems of the human mind and decision making.",
        rating: 4.6,
        genre: "Psychology",
    },
    {
        id: 4,
        cover_img: "https://covers.openlibrary.org/b/id/10958393-L.jpg",
        title: "Sapiens",
        author: "Yuval Noah Harari",
        description: "A brief history of humankind, exploring culture, science, and civilization.",
        rating: 4.8,
        genre: "Anthropology",
    },
    {
        id: 5,
        cover_img: "https://covers.openlibrary.org/b/id/10416442-L.jpg",
        title: "Deep Work",
        author: "Cal Newport",
        description: "Practical strategies for focused success in a distracted world.",
        rating: 4.4,
        genre: "Self-help",
    },
    {
        id: 6,
        cover_img: "https://covers.openlibrary.org/b/id/8235041-L.jpg",
        title: "Dune",
        author: "Frank Herbert",
        description: "A sci-fi epic of politics, religion, and power on the desert planet of Arrakis.",
        rating: 4.6,
        genre: "Science Fiction",
    },
    {
        id: 7,
        cover_img: "https://covers.openlibrary.org/b/id/9285054-L.jpg",
        title: "1984",
        author: "George Orwell",
        description: "A dystopian novel warning against totalitarianism and surveillance.",
        rating: 4.8,
        genre: "Fiction",
    },
    {
        id: 8,
        cover_img: "https://covers.openlibrary.org/b/id/7222246-L.jpg",
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        description: "A powerful novel on racial injustice and moral growth in the American South.",
        rating: 4.9,
        genre: "Fiction",
    },
    {
        id: 9,
        cover_img: "https://covers.openlibrary.org/b/id/10250863-L.jpg",
        title: "Educated",
        author: "Tara Westover",
        description: "A memoir of a woman who escapes a survivalist upbringing to seek education.",
        rating: 4.6,
        genre: "Biography",
    },
    {
        id: 10,
        cover_img: "https://covers.openlibrary.org/b/id/8155080-L.jpg",
        title: "Atomic Habits",
        author: "James Clear",
        description: "An actionable guide to building good habits and breaking bad ones.",
        rating: 4.6,
        genre: "Self-help",
    },
    {
        id: 11,
        cover_img: "https://covers.openlibrary.org/b/id/10445192-L.jpg",
        title: "The Hobbit",
        author: "J.R.R. Tolkien",
        description: "A fantasy adventure that sets the stage for the epic Lord of the Rings trilogy.",
        rating: 4.9,
        genre: "Fantasy",
    },
    {
        id: 12,
        cover_img: "https://covers.openlibrary.org/b/id/10978858-L.jpg",
        title: "Becoming",
        author: "Michelle Obama",
        description: "An intimate memoir by the former First Lady of the United States.",
        rating: 4.6,
        genre: "Biography",
    },
    {
        id: 13,
        cover_img: "https://covers.openlibrary.org/b/id/11154858-L.jpg",
        title: "The Martian",
        author: "Andy Weir",
        description: "A stranded astronaut uses science and wit to survive on Mars.",
        rating: 4.7,
        genre: "Science Fiction",
    },
    {
        id: 14,
        cover_img: "https://covers.openlibrary.org/b/id/10038382-L.jpg",
        title: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        description: "A tragic tale of love, ambition, and the American dream in the Jazz Age.",
        rating: 4.5,
        genre: "Classic",
    },
    {
        id: 15,
        cover_img: "https://covers.openlibrary.org/b/id/10860972-L.jpg",
        title: "The Subtle Art of Not Giving a F*ck",
        author: "Mark Manson",
        description: "A blunt, humorous approach to living a meaningful life.",
        rating: 4.3,
        genre: "Self-help",
    },
    {
        id: 16,
        cover_img: "https://covers.openlibrary.org/b/id/8706873-L.jpg",
        title: "Pride and Prejudice",
        author: "Jane Austen",
        description: "A classic romantic novel exploring manners, marriage, and morality.",
        rating: 4.7,
        genre: "Romance",
    },
    {
        id: 17,
        cover_img: "https://covers.openlibrary.org/b/id/11106050-L.jpg",
        title: "A Brief History of Time",
        author: "Stephen Hawking",
        description: "A popular science book explaining complex theories of time and space.",
        rating: 4.4,
        genre: "Science",
    },
    {
        id: 18,
        cover_img: "https://covers.openlibrary.org/b/id/8154206-L.jpg",
        title: "The Catcher in the Rye",
        author: "J.D. Salinger",
        description: "A story of teenage angst and alienation in post-war America.",
        rating: 4.2,
        genre: "Fiction",
    },
    {
        id: 19,
        cover_img: "https://covers.openlibrary.org/b/id/10984145-L.jpg",
        title: "The Alchemist",
        author: "Paulo Coelho",
        description: "A spiritual fable about following your dreams and listening to your heart.",
        rating: 4.5,
        genre: "Fiction",
    },
    {
        id: 20,
        cover_img: "https://covers.openlibrary.org/b/id/10512907-L.jpg",
        title: "Brave New World",
        author: "Aldous Huxley",
        description: "A dystopian classic envisioning a future shaped by technological control and conformity.",
        rating: 4.6,
        genre: "Science Fiction",
    },
    {
        id: 21,
        cover_img: "https://covers.openlibrary.org/b/id/10416443-L.jpg",
        title: "The Guns of August",
        author: "Barbara W. Tuchman",
        description: "A masterful account of the first month of World War I.",
        rating: 4.7,
        genre: "History",
    },
    {
        id: 22,
        cover_img: "https://covers.openlibrary.org/b/id/10416444-L.jpg",
        title: "Meditations",
        author: "Marcus Aurelius",
        description: "Personal writings of the Roman Emperor on Stoic philosophy.",
        rating: 4.6,
        genre: "Philosophy",
    },
    {
        id: 23,
        cover_img: "https://covers.openlibrary.org/b/id/10416445-L.jpg",
        title: "The Power of Habit",
        author: "Charles Duhigg",
        description: "Exploring the science behind habit formation and change.",
        rating: 4.5,
        genre: "Self-help",
    },
    {
        id: 24,
        cover_img: "https://covers.openlibrary.org/b/id/10416446-L.jpg",
        title: "Project Hail Mary",
        author: "Andy Weir",
        description: "A thrilling space adventure about survival and friendship.",
        rating: 4.6,
        genre: "Science Fiction",
    },
    {
        id: 25,
        cover_img: "https://covers.openlibrary.org/b/id/10416447-L.jpg",
        title: "The Midnight Library",
        author: "Matt Haig",
        description: "A novel about infinite possibilities and the choices that make up a life.",
        rating: 4.4,
        genre: "Fiction",
    },
    {
        id: 26,
        cover_img: "https://covers.openlibrary.org/b/id/10416448-L.jpg",
        title: "Steve Jobs",
        author: "Walter Isaacson",
        description: "The authorized biography of the Apple co-founder.",
        rating: 4.6,
        genre: "Biography",
    },
    {
        id: 27,
        cover_img: "https://covers.openlibrary.org/b/id/10416449-L.jpg",
        title: "The Name of the Wind",
        author: "Patrick Rothfuss",
        description: "An epic fantasy about a legendary musician and magician.",
        rating: 4.9,
        genre: "Fantasy",
    },
    {
        id: 28,
        cover_img: "https://covers.openlibrary.org/b/id/10416450-L.jpg",
        title: "The Seven Husbands of Evelyn Hugo",
        author: "Taylor Jenkins Reid",
        description: "A reclusive Hollywood legend reveals her life story.",
        rating: 4.6,
        genre: "Fiction",
    },
    {
        id: 29,
        cover_img: "https://covers.openlibrary.org/b/id/10416451-L.jpg",
        title: "A Brief History of Everything",
        author: "Bill Bryson",
        description: "A journey through time and space, from the Big Bang to modern civilization.",
        rating: 4.5,
        genre: "Science",
    },
    {
        id: 30,
        cover_img: "https://covers.openlibrary.org/b/id/10416452-L.jpg",
        title: "The Psychology of Money",
        author: "Morgan Housel",
        description: "Timeless lessons on wealth, greed, and happiness.",
        rating: 4.5,
        genre: "Psychology",
    },
    {
        id: 31,
        cover_img: "https://covers.openlibrary.org/b/id/10416453-L.jpg",
        title: "The Psychology of Money",
        author: "Morgan Housel",
        description: "Timeless lessons on wealth, greed, and happiness.",
        rating: 4.7,
        genre: "Psychology",
    },
    {
        id: 32,
        cover_img: "https://covers.openlibrary.org/b/id/10416454-L.jpg",
        title: "The Guns of August",
        author: "Barbara W. Tuchman",
        description: "A masterful account of the first month of World War I.",
        rating: 4.7,
        genre: "History",
    },
    {
        id: 33,
        cover_img: "https://covers.openlibrary.org/b/id/10416455-L.jpg",
        title: "The Midnight Library",
        author: "Matt Haig",
        description: "A novel about infinite possibilities and the choices that make up a life.",
        rating: 4.4,
        genre: "Fiction",
    },
    {
        id: 34,
        cover_img: "https://covers.openlibrary.org/b/id/10416456-L.jpg",
        title: "Project Hail Mary",
        author: "Andy Weir",
        description: "A thrilling space adventure about survival and friendship.",
        rating: 4.8,
        genre: "Science Fiction",
    },
    {
        id: 35,
        cover_img: "https://covers.openlibrary.org/b/id/10416457-L.jpg",
        title: "The Power of Habit",
        author: "Charles Duhigg",
        description: "Exploring the science behind habit formation and change.",
        rating: 4.5,
        genre: "Self-help",
    },
    {
        id: 36,
        cover_img: "https://covers.openlibrary.org/b/id/10416458-L.jpg",
        title: "Meditations",
        author: "Marcus Aurelius",
        description: "Personal writings of the Roman Emperor on Stoic philosophy.",
        rating: 4.6,
        genre: "Philosophy",
    },
    {
        id: 37,
        cover_img: "https://covers.openlibrary.org/b/id/10416459-L.jpg",
        title: "The Name of the Wind",
        author: "Patrick Rothfuss",
        description: "An epic fantasy about a legendary musician and magician.",
        rating: 4.9,
        genre: "Fantasy",
    },
    {
        id: 38,
        cover_img: "https://covers.openlibrary.org/b/id/10416460-L.jpg",
        title: "Steve Jobs",
        author: "Walter Isaacson",
        description: "The authorized biography of the Apple co-founder.",
        rating: 4.7,
        genre: "Biography",
    },
    {
        id: 39,
        cover_img: "https://covers.openlibrary.org/b/id/10416461-L.jpg",
        title: "A Brief History of Everything",
        author: "Bill Bryson",
        description: "A journey through time and space, from the Big Bang to modern civilization.",
        rating: 4.5,
        genre: "Science",
    },
    {
        id: 40,
        cover_img: "https://covers.openlibrary.org/b/id/10416462-L.jpg",
        title: "The Seven Husbands of Evelyn Hugo",
        author: "Taylor Jenkins Reid",
        description: "A reclusive Hollywood legend reveals her life story.",
        rating: 4.6,
        genre: "Fiction",
    },
    {
        id: 41,
        cover_img: "https://covers.openlibrary.org/b/id/10416463-L.jpg",
        title: "The Notebook",
        author: "Nicholas Sparks",
        description: "A timeless love story about a couple's enduring romance through the decades.",
        rating: 4.6,
        genre: "Romance",
    },
    {
        id: 42,
        cover_img: "https://covers.openlibrary.org/b/id/10416464-L.jpg",
        title: "Outlander",
        author: "Diana Gabaldon",
        description: "A sweeping historical romance that spans centuries and continents.",
        rating: 4.6,
        genre: "Romance",
    },
    {
        id: 43,
        cover_img: "https://covers.openlibrary.org/b/id/10416465-L.jpg",
        title: "The Time Traveler's Wife",
        author: "Audrey Niffenegger",
        description: "A unique love story about a man with a genetic disorder that causes him to time travel.",
        rating: 4.5,
        genre: "Romance",
    },
    {
        id: 44,
        cover_img: "https://covers.openlibrary.org/b/id/10416466-L.jpg",
        title: "Me Before You",
        author: "Jojo Moyes",
        description: "A heartwarming and heartbreaking love story about finding joy in unexpected places.",
        rating: 4.6,
        genre: "Romance",
    },
    {
        id: 45,
        cover_img: "https://covers.openlibrary.org/b/id/10416467-L.jpg",
        title: "Guns, Germs, and Steel",
        author: "Jared Diamond",
        description: "A Pulitzer Prize-winning exploration of why human societies developed differently across the globe.",
        rating: 4.7,
        genre: "Anthropology",
    }
];
